### ISSUE TITLE
Tinymce does not recognize locale change

### ISSUE THREAD

**Issue by artworkad** [stfalcon/TinymceBundle#140]
Hi, I have this in my config.yml

```
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: false
    language: %locale%
```

the language will only change when I hardcode the locale. I am using

```
http://jmsyst.com/bundles/JMSTranslationBundle
```

and changing the language in url like from

```
mysite.com/en/foobar
```

to

```
mysite.com/de/foobar
```

does not change the tinymce language. Any ideas?
