### ISSUE TITLE
How to configure “formats” in config.yml ?

### ISSUE THREAD

**Issue by LeFredd** [stfalcon/TinymceBundle#153]
Hi,

I want to set the "format" option stfalcon / TinymceBundle but I can not. I consulted the documentation stfalcon / TinymceBundle and also TinyMCE, I do more tests but without results. What I want to do: when you click on the button "formats", you can just select the title "h1, h2 ..." and block "div and p". I do not want the settings faultless.

On official documentation of TinyMCE I saw the need to use "style_format" : configuration style_format

But they go through the arguments of the initialization of tinyMCE () function:

```
tinymce.init({
style_formats: [
{title: "Headers", items: [
    {title: "Header 1", format: "h1"},
    {title: "Header 2", format: "h2"},
    {title: "Header 3", format: "h3"},
    {title: "Header 4", format: "h4"},
    {title: "Header 5", format: "h5"},
    {title: "Header 6", format: "h6"}
]},
{title: "Inline", items: [
    {title: "Bold", icon: "bold", format: "bold"},
    {title: "Italic", icon: "italic", format: "italic"},
    {title: "Underline", icon: "underline", format: "underline"},
    {title: "Strikethrough", icon: "strikethrough", format: "strikethrough"},
    ...
]
});
```

But I have to go through the Symfony2 config.yml file to set tinyMCE. I have set other parameters in this file and everything works except for style_formats.

How do I do this? Here is my config.yml I left my line style_formats (which does not work but does not generate an error):

```
stfalcon_tinymce:
selector: ".tinymce"
language: %locale%
external_plugins:
    filemanager:
        url: "asset[bundles/ResponsiveFilemanager-master/filemanager/plugin.min.js]"
theme:
    # Simple theme: same as default theme
    simple: ~
    # Advanced theme with almost all enabled plugins
    advanced:
        style_format:
            { title: 'Headers', items: {'title': 'Header 1', 'format': 'h1'} }
        menu:
            insert: { title: 'Insert', items: 'hr | charmap | insertdatetime' }
            view: { title : 'View', items : 'visualaid | fullscreen | preview | visualblocks visualchars | code' }
            table: { title : 'Table' , items: 'inserttable tableprops deletetable | cell row column' }
        relative_urls: false
        external_filemanager_path: "../../../web/bundles/ResponsiveFilemanager-master/filemanager/"
        filemanager_title: "File Manager"
        plugins:
            - "advlist autosave autolink lists link image charmap preview hr pagebreak"
            - "wordcount visualblocks visualchars code fullscreen"
            - "insertdatetime nonbreaking save table directionality"
            - "emoticons template paste textcolor responsivefilemanager"
        toolbar1: "undo redo | forecolor backcolor | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image emoticons"
        toolbar2: "code preview | fontsizeselect styleselect"
        image_advtab: false
```

I also try going through the arguments of the function in twig taking the model of the doc stfalcon / tinymce Bundle Documentation tinyMCE Bundle github:

```
{% block javascripts %}
{{ tinymce_init({'style_formats': {'title': 'Headers', {'items':
    {'title': 'Header 1', 'format': 'h1'},
    {'title': 'Header 2', 'format': 'h2'},
    {'title': 'Header 3', 'format': 'h3'},
    {'title': 'Header 4', 'format': 'h4'},
    {'title': 'Header 5', 'format': 'h5'},
    {'title': 'Header 6', 'format': 'h6'}}}
}) }}

{% endblock %}
```

But still no result. Could you help me?
