### ISSUE TITLE
Multiple custom buttons don't work

### ISSUE THREAD

**Issue by benr77** [stfalcon/TinymceBundle#52]
If I define a custom button as described in your docs, it works fine.

However, if I define multiple custom buttons, only the last one defined is shown in the TinyMCE editor.

I've tested this by switching the order in the config, and all work individually, but only the last one shown is defined.

In config.yml I have:

```
tinymce_buttons:
    mybutton1:
        title: "Insert snippet A"
        image: "asset[bundles/mybundle/images/icons/A.png]"
    mybutton2:                                      
        title: "Insert snippet B"                   
        image: "asset[bundles/mybundle/images/icons/B.png]"
    mybutton3:                                      
        title: "Insert snippet C"
        image: "asset[bundles/mybundle/images/icons/C.png]" 
```
