### ISSUE TITLE
Add details about "content_css" parameter to readme

### ISSUE THREAD

**Issue by benr77** [stfalcon/TinymceBundle#54]
It would be handy to add details to the readme about using the content_css parameter to allow custom styling of the editing area content.

The setting I found to work in config.yml is:

```
theme:
        simple:
            content_css: "/bundles/mybundle/css/tinymce-content.css"
            mode: "textareas"
            ....
```

I spent ages having this parameter in the top level of the config block and it was being ignored. As soon as I moved it in to the theme specific config block things started working properly.

Thanks
Ben
