### ISSUE TITLE
Configuration fails

### ISSUE THREAD

**Issue by cursedcoder** [stfalcon/TinymceBundle#63]
``` yaml
stfalcon_tinymce:
    theme:
        content:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "styleselect,bold,italic,separator,justifyleft,justifycenter,justifyright,bullist,link,separator,code,separator,pagebreak"
            pagebreak_separator: "</p><!-- pagebreak --><p>"
            plugins: "pagebreak"
            style_formats:
                -
                    title: Paragraph
                    block: p
                -
                    title: Header
                    block: h2
```

```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]                                   
  Invalid type for path "stfalcon_tinymce.theme.content.style_formats". Expected scalar, but got array.
```
